/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maquetageAdmin;

/**
 *
 * @author Wolf
 */
public class RechercheAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RechercheAdmin
     */
    public RechercheAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpFenetreAdmin = new javax.swing.JTabbedPane();
        pnOngletRechercheAdmin = new javax.swing.JPanel();
        pnTypeRechercheOngletRechercheAdmin = new javax.swing.JPanel();
        lbTypeRechercheOngletRechercheAdmin = new javax.swing.JLabel();
        cbTypeRechercheOngletRechercheAdmin = new javax.swing.JComboBox();
        pnRechercheIdentifiantOngletRechercheAdmin = new javax.swing.JPanel();
        lbIdentifiantOngletRechercheAdmin = new javax.swing.JLabel();
        tfIdentifiantOngletRechercheAdmin = new javax.swing.JTextField();
        pnRechercheAvanceeOngletRechercheAdmin = new javax.swing.JPanel();
        lbTokenOngletRechercheAdmin = new javax.swing.JLabel();
        lbDeOngletRechercheAdmin = new javax.swing.JLabel();
        tfMinTokenOngletRechercheAdmin = new javax.swing.JTextField();
        lbRegionOngletRechercheAdmin = new javax.swing.JLabel();
        cbRegionOngletRechercheAdmin = new javax.swing.JComboBox();
        lbAOngletRechercheAdmin = new javax.swing.JLabel();
        tfMaxTokenOngletRechercheAdmin = new javax.swing.JTextField();
        lbCategoriesOngletRechercheAdmin = new javax.swing.JLabel();
        cbCategoriesOngletRechercheAdmin = new javax.swing.JComboBox();
        btChercherOngletRechercheAdmin = new javax.swing.JButton();
        spResultatOngletRechercheAdmin = new javax.swing.JScrollPane();
        tbResultatOngletRechercheAdmin = new javax.swing.JTable();
        btSupprimerOngletRechercheAdmin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lAjoutObjet = new javax.swing.JLabel();
        pDetailsObjet = new javax.swing.JPanel();
        lTitreAjoutObjet = new javax.swing.JLabel();
        tfAjoutObjet = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpFenetreAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnTypeRechercheOngletRechercheAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbTypeRechercheOngletRechercheAdmin.setText("Que cherchez-vous ?");

        cbTypeRechercheOngletRechercheAdmin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "services", "objets" }));
        cbTypeRechercheOngletRechercheAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeRechercheOngletRechercheAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTypeRechercheOngletRechercheAdminLayout = new javax.swing.GroupLayout(pnTypeRechercheOngletRechercheAdmin);
        pnTypeRechercheOngletRechercheAdmin.setLayout(pnTypeRechercheOngletRechercheAdminLayout);
        pnTypeRechercheOngletRechercheAdminLayout.setHorizontalGroup(
            pnTypeRechercheOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTypeRechercheOngletRechercheAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTypeRechercheOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbTypeRechercheOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        pnTypeRechercheOngletRechercheAdminLayout.setVerticalGroup(
            pnTypeRechercheOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTypeRechercheOngletRechercheAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTypeRechercheOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTypeRechercheOngletRechercheAdmin)
                    .addComponent(cbTypeRechercheOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnRechercheIdentifiantOngletRechercheAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnRechercheIdentifiantOngletRechercheAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnRechercheIdentifiantOngletRechercheAdminMouseClicked(evt);
            }
        });

        lbIdentifiantOngletRechercheAdmin.setText("Identifiant : ");
        lbIdentifiantOngletRechercheAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIdentifiantOngletRechercheAdminMouseClicked(evt);
            }
        });

        tfIdentifiantOngletRechercheAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIdentifiantOngletRechercheAdminMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfIdentifiantOngletRechercheAdminMouseReleased(evt);
            }
        });
        tfIdentifiantOngletRechercheAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdentifiantOngletRechercheAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnRechercheIdentifiantOngletRechercheAdminLayout = new javax.swing.GroupLayout(pnRechercheIdentifiantOngletRechercheAdmin);
        pnRechercheIdentifiantOngletRechercheAdmin.setLayout(pnRechercheIdentifiantOngletRechercheAdminLayout);
        pnRechercheIdentifiantOngletRechercheAdminLayout.setHorizontalGroup(
            pnRechercheIdentifiantOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRechercheIdentifiantOngletRechercheAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIdentifiantOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfIdentifiantOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        pnRechercheIdentifiantOngletRechercheAdminLayout.setVerticalGroup(
            pnRechercheIdentifiantOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRechercheIdentifiantOngletRechercheAdminLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pnRechercheIdentifiantOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentifiantOngletRechercheAdmin)
                    .addComponent(tfIdentifiantOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnRechercheAvanceeOngletRechercheAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "recherche avancée"));
        pnRechercheAvanceeOngletRechercheAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnRechercheAvanceeOngletRechercheAdminMouseClicked(evt);
            }
        });

        lbTokenOngletRechercheAdmin.setText("Tokens :");

        lbDeOngletRechercheAdmin.setText("de");

        lbRegionOngletRechercheAdmin.setText("Région :");
        lbRegionOngletRechercheAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRegionOngletRechercheAdminMouseClicked(evt);
            }
        });

        cbRegionOngletRechercheAdmin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "     ", "Ariana", "Béja", "Ben Arous", "Bizerte", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kébili", "Kef", "Mahdia", "Manouba", "Médenine", "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliana", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouan" }));
        cbRegionOngletRechercheAdmin.setName("Region"); // NOI18N
        cbRegionOngletRechercheAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbRegionOngletRechercheAdminMouseClicked(evt);
            }
        });

        lbAOngletRechercheAdmin.setText("à");

        tfMaxTokenOngletRechercheAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaxTokenOngletRechercheAdminActionPerformed(evt);
            }
        });

        lbCategoriesOngletRechercheAdmin.setText("Catégories :");
        lbCategoriesOngletRechercheAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCategoriesOngletRechercheAdminMouseClicked(evt);
            }
        });

        cbCategoriesOngletRechercheAdmin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "bricolage", "hibergement", "plomberie", "covoiturage", "jardinage", "electricité", "demenagement", "TIC", "mecanique", "reparation", "autres" }));
        cbCategoriesOngletRechercheAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCategoriesOngletRechercheAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnRechercheAvanceeOngletRechercheAdminLayout = new javax.swing.GroupLayout(pnRechercheAvanceeOngletRechercheAdmin);
        pnRechercheAvanceeOngletRechercheAdmin.setLayout(pnRechercheAvanceeOngletRechercheAdminLayout);
        pnRechercheAvanceeOngletRechercheAdminLayout.setHorizontalGroup(
            pnRechercheAvanceeOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRechercheAvanceeOngletRechercheAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRechercheAvanceeOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRechercheAvanceeOngletRechercheAdminLayout.createSequentialGroup()
                        .addComponent(lbRegionOngletRechercheAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(cbRegionOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(lbCategoriesOngletRechercheAdmin)
                        .addGap(87, 87, 87)
                        .addComponent(cbCategoriesOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(pnRechercheAvanceeOngletRechercheAdminLayout.createSequentialGroup()
                        .addComponent(lbTokenOngletRechercheAdmin)
                        .addGap(5, 5, 5)
                        .addComponent(lbDeOngletRechercheAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMinTokenOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMaxTokenOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnRechercheAvanceeOngletRechercheAdminLayout.setVerticalGroup(
            pnRechercheAvanceeOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRechercheAvanceeOngletRechercheAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnRechercheAvanceeOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRegionOngletRechercheAdmin)
                    .addComponent(cbRegionOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCategoriesOngletRechercheAdmin)
                    .addComponent(cbCategoriesOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnRechercheAvanceeOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTokenOngletRechercheAdmin)
                    .addComponent(lbDeOngletRechercheAdmin)
                    .addComponent(tfMinTokenOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAOngletRechercheAdmin)
                    .addComponent(tfMaxTokenOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btChercherOngletRechercheAdmin.setText("Chercher");
        btChercherOngletRechercheAdmin.setHideActionText(true);
        btChercherOngletRechercheAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btChercherOngletRechercheAdmin.setName("btChercherOngletRechercheAdmin"); // NOI18N

        tbResultatOngletRechercheAdmin.setAutoCreateRowSorter(true);
        tbResultatOngletRechercheAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbResultatOngletRechercheAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificateur", "Titre", "Catégorie", "Date de publication", "Description", "Tokens", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbResultatOngletRechercheAdmin.setCellSelectionEnabled(true);
        spResultatOngletRechercheAdmin.setViewportView(tbResultatOngletRechercheAdmin);

        btSupprimerOngletRechercheAdmin.setText("Supprimer");

        javax.swing.GroupLayout pnOngletRechercheAdminLayout = new javax.swing.GroupLayout(pnOngletRechercheAdmin);
        pnOngletRechercheAdmin.setLayout(pnOngletRechercheAdminLayout);
        pnOngletRechercheAdminLayout.setHorizontalGroup(
            pnOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOngletRechercheAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btChercherOngletRechercheAdmin)
                        .addGroup(pnOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnTypeRechercheOngletRechercheAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnRechercheIdentifiantOngletRechercheAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnRechercheAvanceeOngletRechercheAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btSupprimerOngletRechercheAdmin)
                        .addComponent(spResultatOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnOngletRechercheAdminLayout.setVerticalGroup(
            pnOngletRechercheAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOngletRechercheAdminLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pnTypeRechercheOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnRechercheIdentifiantOngletRechercheAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnRechercheAvanceeOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btChercherOngletRechercheAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spResultatOngletRechercheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSupprimerOngletRechercheAdmin)
                .addGap(316, 316, 316))
        );

        tpFenetreAdmin.addTab("Recherche", pnOngletRechercheAdmin);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        tpFenetreAdmin.addTab("Profil", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        tpFenetreAdmin.addTab("Services", jPanel3);

        lAjoutObjet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lAjoutObjet.setText("Ajouter un objet");

        pDetailsObjet.setBorder(javax.swing.BorderFactory.createTitledBorder("Détails de l'objet"));

        lTitreAjoutObjet.setText("Titre :");

        jLabel23.setText("Catégorie :");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "              ", "Jardinage", "Bricolage", "Cuisine", "TIC" }));

        jLabel24.setText("Tockens demandés :");

        jLabel25.setText("Date :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel26.setText("du");

        jFormattedTextField5.setText("          ..   /   ..    /   ..");
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });

        jFormattedTextField6.setText("          ..   /   ..    /   ..");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel27.setText("à");

        jLabel28.setText("Descrition :");

        jButton3.setText("Parcourir");

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel30.setText("Images :");

        javax.swing.GroupLayout pDetailsObjetLayout = new javax.swing.GroupLayout(pDetailsObjet);
        pDetailsObjet.setLayout(pDetailsObjetLayout);
        pDetailsObjetLayout.setHorizontalGroup(
            pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailsObjetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDetailsObjetLayout.createSequentialGroup()
                        .addGroup(pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(lTitreAjoutObjet)
                            .addComponent(jLabel23)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAjoutObjet)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDetailsObjetLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDetailsObjetLayout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel30))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pDetailsObjetLayout.setVerticalGroup(
            pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailsObjetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitreAjoutObjet)
                    .addComponent(tfAjoutObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pDetailsObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDetailsObjetLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(pDetailsObjetLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(pDetailsObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lAjoutObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(521, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(pDetailsObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(lAjoutObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(426, Short.MAX_VALUE)))
        );

        tpFenetreAdmin.addTab("Objet", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpFenetreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpFenetreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTypeRechercheOngletRechercheAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeRechercheOngletRechercheAdminActionPerformed
        String selectedItem=(String)cbTypeRechercheOngletRechercheAdmin.getSelectedItem();
        lbCategoriesOngletRechercheAdmin.setEnabled(true);//labelCategories.setVisible(true);
        cbCategoriesOngletRechercheAdmin.setEnabled(true);//categories.setVisible(true);
        if (selectedItem.equals("objets"))
        {lbCategoriesOngletRechercheAdmin.setEnabled(false);//labelCategories.setVisible(false);
            cbCategoriesOngletRechercheAdmin.setEnabled(false);//categories.setVisible(false);
        }
    }//GEN-LAST:event_cbTypeRechercheOngletRechercheAdminActionPerformed

    private void lbIdentifiantOngletRechercheAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIdentifiantOngletRechercheAdminMouseClicked
        lbIdentifiantOngletRechercheAdmin.setEnabled(true);
        tfIdentifiantOngletRechercheAdmin.setEnabled(true);
        lbCategoriesOngletRechercheAdmin.setEnabled(false);//labelCategories.setVisible(false);
        cbCategoriesOngletRechercheAdmin.setEnabled(false);
        lbRegionOngletRechercheAdmin.setEnabled(false);
        cbRegionOngletRechercheAdmin.setEnabled(false);
        lbTokenOngletRechercheAdmin.setEnabled(false);
        tfMinTokenOngletRechercheAdmin.setEnabled(false);
        tfMaxTokenOngletRechercheAdmin.setEnabled(false);
        lbDeOngletRechercheAdmin.setEnabled(false);
        lbAOngletRechercheAdmin.setEnabled(false);
    }//GEN-LAST:event_lbIdentifiantOngletRechercheAdminMouseClicked

    private void tfIdentifiantOngletRechercheAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIdentifiantOngletRechercheAdminMouseClicked
        lbIdentifiantOngletRechercheAdmin.setEnabled(true);
        tfIdentifiantOngletRechercheAdmin.setEnabled(true);
        lbCategoriesOngletRechercheAdmin.setEnabled(false);//labelCategories.setVisible(false);
        cbCategoriesOngletRechercheAdmin.setEnabled(false);
        lbRegionOngletRechercheAdmin.setEnabled(false);
        cbRegionOngletRechercheAdmin.setEnabled(false);
        lbTokenOngletRechercheAdmin.setEnabled(false);
        tfMinTokenOngletRechercheAdmin.setEnabled(false);
        tfMaxTokenOngletRechercheAdmin.setEnabled(false);
        lbDeOngletRechercheAdmin.setEnabled(false);
        lbAOngletRechercheAdmin.setEnabled(false);

    }//GEN-LAST:event_tfIdentifiantOngletRechercheAdminMouseClicked

    private void tfIdentifiantOngletRechercheAdminMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIdentifiantOngletRechercheAdminMouseReleased

    }//GEN-LAST:event_tfIdentifiantOngletRechercheAdminMouseReleased

    private void tfIdentifiantOngletRechercheAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdentifiantOngletRechercheAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdentifiantOngletRechercheAdminActionPerformed

    private void pnRechercheIdentifiantOngletRechercheAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRechercheIdentifiantOngletRechercheAdminMouseClicked
        lbIdentifiantOngletRechercheAdmin.setEnabled(true);
        tfIdentifiantOngletRechercheAdmin.setEnabled(true);
        lbCategoriesOngletRechercheAdmin.setEnabled(false);//labelCategories.setVisible(false);
        cbCategoriesOngletRechercheAdmin.setEnabled(false);
        lbRegionOngletRechercheAdmin.setEnabled(false);
        cbRegionOngletRechercheAdmin.setEnabled(false);
        lbTokenOngletRechercheAdmin.setEnabled(false);
        tfMinTokenOngletRechercheAdmin.setEnabled(false);
        tfMaxTokenOngletRechercheAdmin.setEnabled(false);
        lbDeOngletRechercheAdmin.setEnabled(false);
        lbAOngletRechercheAdmin.setEnabled(false);
    }//GEN-LAST:event_pnRechercheIdentifiantOngletRechercheAdminMouseClicked

    private void lbRegionOngletRechercheAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegionOngletRechercheAdminMouseClicked
        lbCategoriesOngletRechercheAdmin.setEnabled(true);//labelCategories.setVisible(false);
        cbCategoriesOngletRechercheAdmin.setEnabled(true);
        lbRegionOngletRechercheAdmin.setEnabled(true);
        cbRegionOngletRechercheAdmin.setEnabled(true);
        lbTokenOngletRechercheAdmin.setEnabled(true);
        tfMinTokenOngletRechercheAdmin.setEnabled(true);
        tfMaxTokenOngletRechercheAdmin.setEnabled(true);
        lbDeOngletRechercheAdmin.setEnabled(true);
        lbAOngletRechercheAdmin.setEnabled(true);
        lbIdentifiantOngletRechercheAdmin.setEnabled(false);
        tfIdentifiantOngletRechercheAdmin.setEnabled(false);
    }//GEN-LAST:event_lbRegionOngletRechercheAdminMouseClicked

    private void cbRegionOngletRechercheAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRegionOngletRechercheAdminMouseClicked
        lbCategoriesOngletRechercheAdmin.setEnabled(true);//labelCategories.setVisible(false);
        cbCategoriesOngletRechercheAdmin.setEnabled(true);
        lbRegionOngletRechercheAdmin.setEnabled(true);
        cbRegionOngletRechercheAdmin.setEnabled(true);
        lbTokenOngletRechercheAdmin.setEnabled(true);
        tfMinTokenOngletRechercheAdmin.setEnabled(true);
        tfMaxTokenOngletRechercheAdmin.setEnabled(true);
        lbDeOngletRechercheAdmin.setEnabled(true);
        lbAOngletRechercheAdmin.setEnabled(true);
        lbIdentifiantOngletRechercheAdmin.setEnabled(false);
        tfIdentifiantOngletRechercheAdmin.setEnabled(false);
    }//GEN-LAST:event_cbRegionOngletRechercheAdminMouseClicked

    private void tfMaxTokenOngletRechercheAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaxTokenOngletRechercheAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaxTokenOngletRechercheAdminActionPerformed

    private void lbCategoriesOngletRechercheAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCategoriesOngletRechercheAdminMouseClicked
        lbCategoriesOngletRechercheAdmin.setEnabled(true);//labelCategories.setVisible(false);
        cbCategoriesOngletRechercheAdmin.setEnabled(true);
        lbRegionOngletRechercheAdmin.setEnabled(true);
        cbRegionOngletRechercheAdmin.setEnabled(true);
        lbTokenOngletRechercheAdmin.setEnabled(true);
        tfMinTokenOngletRechercheAdmin.setEnabled(true);
        tfMaxTokenOngletRechercheAdmin.setEnabled(true);
        lbDeOngletRechercheAdmin.setEnabled(true);
        lbAOngletRechercheAdmin.setEnabled(true);
        lbIdentifiantOngletRechercheAdmin.setEnabled(false);
        tfIdentifiantOngletRechercheAdmin.setEnabled(false);
    }//GEN-LAST:event_lbCategoriesOngletRechercheAdminMouseClicked

    private void cbCategoriesOngletRechercheAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCategoriesOngletRechercheAdminMouseClicked
        lbCategoriesOngletRechercheAdmin.setEnabled(true);//labelCategories.setVisible(false);
        cbCategoriesOngletRechercheAdmin.setEnabled(true);
        lbRegionOngletRechercheAdmin.setEnabled(true);
        cbRegionOngletRechercheAdmin.setEnabled(true);
        lbTokenOngletRechercheAdmin.setEnabled(true);
        tfMinTokenOngletRechercheAdmin.setEnabled(true);
        tfMaxTokenOngletRechercheAdmin.setEnabled(true);
        lbDeOngletRechercheAdmin.setEnabled(true);
        lbAOngletRechercheAdmin.setEnabled(true);
        lbIdentifiantOngletRechercheAdmin.setEnabled(false);
        tfIdentifiantOngletRechercheAdmin.setEnabled(false);
    }//GEN-LAST:event_cbCategoriesOngletRechercheAdminMouseClicked

    private void pnRechercheAvanceeOngletRechercheAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRechercheAvanceeOngletRechercheAdminMouseClicked
        String selectedItem=(String)cbTypeRechercheOngletRechercheAdmin.getSelectedItem();
        if (selectedItem.equals("objets"))
        {lbCategoriesOngletRechercheAdmin.setEnabled(false);//labelCategories.setVisible(false);
            cbCategoriesOngletRechercheAdmin.setEnabled(false);//categories.setVisible(false);
            lbRegionOngletRechercheAdmin.setEnabled(true);
            cbRegionOngletRechercheAdmin.setEnabled(true);
            lbTokenOngletRechercheAdmin.setEnabled(true);
            tfMinTokenOngletRechercheAdmin.setEnabled(true);
            tfMaxTokenOngletRechercheAdmin.setEnabled(true);
            lbDeOngletRechercheAdmin.setEnabled(true);
            lbAOngletRechercheAdmin.setEnabled(true);
            lbIdentifiantOngletRechercheAdmin.setEnabled(false);
            tfIdentifiantOngletRechercheAdmin.setEnabled(false);
        }

    }//GEN-LAST:event_pnRechercheAvanceeOngletRechercheAdminMouseClicked

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RechercheAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChercherOngletRechercheAdmin;
    private javax.swing.JButton btSupprimerOngletRechercheAdmin;
    private javax.swing.JComboBox cbCategoriesOngletRechercheAdmin;
    private javax.swing.JComboBox cbRegionOngletRechercheAdmin;
    private javax.swing.JComboBox cbTypeRechercheOngletRechercheAdmin;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lAjoutObjet;
    private javax.swing.JLabel lTitreAjoutObjet;
    private javax.swing.JLabel lbAOngletRechercheAdmin;
    private javax.swing.JLabel lbCategoriesOngletRechercheAdmin;
    private javax.swing.JLabel lbDeOngletRechercheAdmin;
    private javax.swing.JLabel lbIdentifiantOngletRechercheAdmin;
    private javax.swing.JLabel lbRegionOngletRechercheAdmin;
    private javax.swing.JLabel lbTokenOngletRechercheAdmin;
    private javax.swing.JLabel lbTypeRechercheOngletRechercheAdmin;
    private javax.swing.JPanel pDetailsObjet;
    private javax.swing.JPanel pnOngletRechercheAdmin;
    private javax.swing.JPanel pnRechercheAvanceeOngletRechercheAdmin;
    private javax.swing.JPanel pnRechercheIdentifiantOngletRechercheAdmin;
    private javax.swing.JPanel pnTypeRechercheOngletRechercheAdmin;
    private javax.swing.JScrollPane spResultatOngletRechercheAdmin;
    private javax.swing.JTable tbResultatOngletRechercheAdmin;
    private javax.swing.JTextField tfAjoutObjet;
    private javax.swing.JTextField tfIdentifiantOngletRechercheAdmin;
    private javax.swing.JTextField tfMaxTokenOngletRechercheAdmin;
    private javax.swing.JTextField tfMinTokenOngletRechercheAdmin;
    private javax.swing.JTabbedPane tpFenetreAdmin;
    // End of variables declaration//GEN-END:variables
}
