/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maquetage;

/**
 *
 * @author Wolf
 */
public class AjouterObjet extends javax.swing.JFrame {

    /**
     * Creates new form AjouterObjet
     */
    public AjouterObjet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAjouterObjet = new javax.swing.JPanel();
        lbTitrePanelAjouterObjet = new javax.swing.JLabel();
        pnDetailAjouterObjet = new javax.swing.JPanel();
        lbTitreAjouterObjet = new javax.swing.JLabel();
        tfTitreAjouterObjet = new javax.swing.JTextField();
        lbCategorieAjouterObjet = new javax.swing.JLabel();
        cbCategorieAjouterObjet = new javax.swing.JComboBox();
        lbTokensOffertsAjouterObjet = new javax.swing.JLabel();
        spTokensOffertsAjouterObjet = new javax.swing.JSpinner();
        lbDateAjouterObjet = new javax.swing.JLabel();
        lbDuAjouterObjet = new javax.swing.JLabel();
        ffDateDebutAjouterObjet = new javax.swing.JFormattedTextField();
        ffDateFinAjouterObjet = new javax.swing.JFormattedTextField();
        lbAAjouterObjet = new javax.swing.JLabel();
        lbDescriptionAjouterObjet = new javax.swing.JLabel();
        tfDescriptionAjouterObjet = new javax.swing.JTextField();
        btParcourirAjouterObjet = new javax.swing.JButton();
        lbImageAjouterObjet = new javax.swing.JLabel();
        lbImagesAjouterObjet = new javax.swing.JLabel();
        btAjouterAjouterObjet = new javax.swing.JButton();
        lbBackgroundAjouterObjet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 465));
        getContentPane().setLayout(null);

        pnAjouterObjet.setOpaque(false);

        lbTitrePanelAjouterObjet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTitrePanelAjouterObjet.setText("Ajouter un objet");

        pnDetailAjouterObjet.setBorder(javax.swing.BorderFactory.createTitledBorder("Détails de l'objet"));
        pnDetailAjouterObjet.setOpaque(false);

        lbTitreAjouterObjet.setText("Titre :");

        lbCategorieAjouterObjet.setText("Catégorie :");

        cbCategorieAjouterObjet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "              ", "Jardinage", "Bricolage", "Cuisine", "TIC" }));

        lbTokensOffertsAjouterObjet.setText("Tokens offerts :");

        lbDateAjouterObjet.setText("Date :");

        lbDuAjouterObjet.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lbDuAjouterObjet.setText("du");

        ffDateDebutAjouterObjet.setText("          ..   /   ..    /   ..");
        ffDateDebutAjouterObjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffDateDebutAjouterObjetActionPerformed(evt);
            }
        });

        ffDateFinAjouterObjet.setText("          ..   /   ..    /   ..");

        lbAAjouterObjet.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lbAAjouterObjet.setText("à");

        lbDescriptionAjouterObjet.setText("Descrition :");

        btParcourirAjouterObjet.setText("Parcourir");
        btParcourirAjouterObjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParcourirAjouterObjetActionPerformed(evt);
            }
        });

        lbImageAjouterObjet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImageAjouterObjet.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbImagesAjouterObjet.setText("Images :");

        javax.swing.GroupLayout pnDetailAjouterObjetLayout = new javax.swing.GroupLayout(pnDetailAjouterObjet);
        pnDetailAjouterObjet.setLayout(pnDetailAjouterObjetLayout);
        pnDetailAjouterObjetLayout.setHorizontalGroup(
            pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailAjouterObjetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailAjouterObjetLayout.createSequentialGroup()
                        .addGroup(pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDateAjouterObjet)
                            .addComponent(lbTokensOffertsAjouterObjet)
                            .addComponent(lbTitreAjouterObjet)
                            .addComponent(lbCategorieAjouterObjet)
                            .addComponent(lbDescriptionAjouterObjet))
                        .addGap(18, 18, 18)
                        .addGroup(pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTitreAjouterObjet)
                            .addComponent(spTokensOffertsAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCategorieAjouterObjet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailAjouterObjetLayout.createSequentialGroup()
                                .addComponent(lbDuAjouterObjet)
                                .addGap(18, 18, 18)
                                .addComponent(ffDateDebutAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(lbAAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ffDateFinAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addComponent(tfDescriptionAjouterObjet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailAjouterObjetLayout.createSequentialGroup()
                                .addComponent(lbImageAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btParcourirAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbImagesAjouterObjet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDetailAjouterObjetLayout.setVerticalGroup(
            pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailAjouterObjetLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitreAjouterObjet)
                    .addComponent(tfTitreAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategorieAjouterObjet)
                    .addComponent(cbCategorieAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTokensOffertsAjouterObjet)
                    .addComponent(spTokensOffertsAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDuAjouterObjet)
                    .addComponent(ffDateDebutAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAAjouterObjet)
                    .addComponent(ffDateFinAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescriptionAjouterObjet)
                    .addComponent(tfDescriptionAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnDetailAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailAjouterObjetLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbImagesAjouterObjet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btParcourirAjouterObjet))
                    .addGroup(pnDetailAjouterObjetLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbImageAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        btAjouterAjouterObjet.setText("Ajouter");
        btAjouterAjouterObjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterAjouterObjetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAjouterObjetLayout = new javax.swing.GroupLayout(pnAjouterObjet);
        pnAjouterObjet.setLayout(pnAjouterObjetLayout);
        pnAjouterObjetLayout.setHorizontalGroup(
            pnAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAjouterObjetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAjouterAjouterObjet)
                    .addComponent(pnDetailAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(pnAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnAjouterObjetLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lbTitrePanelAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(469, Short.MAX_VALUE)))
        );
        pnAjouterObjetLayout.setVerticalGroup(
            pnAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAjouterObjetLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(pnDetailAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAjouterAjouterObjet)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(pnAjouterObjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnAjouterObjetLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(lbTitrePanelAjouterObjet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(350, Short.MAX_VALUE)))
        );

        getContentPane().add(pnAjouterObjet);
        pnAjouterObjet.setBounds(50, 60, 600, 380);

        lbBackgroundAjouterObjet.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wolf\\Desktop\\Maquetage\\src\\Images\\fond1.png")); // NOI18N
        getContentPane().add(lbBackgroundAjouterObjet);
        lbBackgroundAjouterObjet.setBounds(0, 0, 650, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAjouterAjouterObjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterAjouterObjetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAjouterAjouterObjetActionPerformed

    private void ffDateDebutAjouterObjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffDateDebutAjouterObjetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffDateDebutAjouterObjetActionPerformed

    private void btParcourirAjouterObjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParcourirAjouterObjetActionPerformed
        ModifierPhoto modifPhoto = new ModifierPhoto();
        modifPhoto.setVisible(true);
    }//GEN-LAST:event_btParcourirAjouterObjetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterObjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterObjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterObjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterObjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterObjet().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouterAjouterObjet;
    private javax.swing.JButton btParcourirAjouterObjet;
    private javax.swing.JComboBox cbCategorieAjouterObjet;
    private javax.swing.JFormattedTextField ffDateDebutAjouterObjet;
    private javax.swing.JFormattedTextField ffDateFinAjouterObjet;
    private javax.swing.JLabel lbAAjouterObjet;
    private javax.swing.JLabel lbBackgroundAjouterObjet;
    private javax.swing.JLabel lbCategorieAjouterObjet;
    private javax.swing.JLabel lbDateAjouterObjet;
    private javax.swing.JLabel lbDescriptionAjouterObjet;
    private javax.swing.JLabel lbDuAjouterObjet;
    private javax.swing.JLabel lbImageAjouterObjet;
    private javax.swing.JLabel lbImagesAjouterObjet;
    private javax.swing.JLabel lbTitreAjouterObjet;
    private javax.swing.JLabel lbTitrePanelAjouterObjet;
    private javax.swing.JLabel lbTokensOffertsAjouterObjet;
    private javax.swing.JPanel pnAjouterObjet;
    private javax.swing.JPanel pnDetailAjouterObjet;
    private javax.swing.JSpinner spTokensOffertsAjouterObjet;
    private javax.swing.JTextField tfDescriptionAjouterObjet;
    private javax.swing.JTextField tfTitreAjouterObjet;
    // End of variables declaration//GEN-END:variables
}
