/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maquetage;

/**
 *
 * @author Wolf
 */
public class AjouterDemandeDeService extends javax.swing.JFrame {

    /**
     * Creates new form AjouterDemandeDeService
     */
    public AjouterDemandeDeService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAjouterDemandeService = new javax.swing.JPanel();
        lbDemanderService = new javax.swing.JLabel();
        pnDetailService = new javax.swing.JPanel();
        lbTitreAjouterDemandeService = new javax.swing.JLabel();
        tfTitreAjouterDemandeService = new javax.swing.JTextField();
        lbCategorieAjouterDemandeService = new javax.swing.JLabel();
        cbCategorieAjouterDemandeService = new javax.swing.JComboBox();
        lbTokensOffertsAjouterDemandeService = new javax.swing.JLabel();
        spTokensOffertsAjouterDemandeService = new javax.swing.JSpinner();
        lbDateAjouterDemandeService = new javax.swing.JLabel();
        lbDuAjouterDemandeService = new javax.swing.JLabel();
        ffDateDebutAjouterDemandeService = new javax.swing.JFormattedTextField();
        ffDateFinAjouterDemandeService = new javax.swing.JFormattedTextField();
        lbAAjouterDemandeService = new javax.swing.JLabel();
        lbDescriptionAjouterDemandeService = new javax.swing.JLabel();
        tfDescriptionAjouterDemandeService = new javax.swing.JTextField();
        btParcourirAjouterDemandeService = new javax.swing.JButton();
        lbImageAjouterDemandeService = new javax.swing.JLabel();
        lbImagesAjouterDemandeService = new javax.swing.JLabel();
        btAjouterDemandeService = new javax.swing.JButton();
        lbBackground = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(691, 515));
        getContentPane().setLayout(null);

        pnAjouterDemandeService.setOpaque(false);

        lbDemanderService.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDemanderService.setText("Demander un service");

        pnDetailService.setBorder(javax.swing.BorderFactory.createTitledBorder("Détails du service"));
        pnDetailService.setOpaque(false);

        lbTitreAjouterDemandeService.setText("Titre :");

        lbCategorieAjouterDemandeService.setText("Catégorie :");

        cbCategorieAjouterDemandeService.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "              ", "Jardinage", "Bricolage", "Cuisine", "TIC" }));

        lbTokensOffertsAjouterDemandeService.setText("Tockens offerts :");

        lbDateAjouterDemandeService.setText("Date :");

        lbDuAjouterDemandeService.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lbDuAjouterDemandeService.setText("du");

        ffDateDebutAjouterDemandeService.setText("          ..   /   ..    /   ..");
        ffDateDebutAjouterDemandeService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffDateDebutAjouterDemandeServiceActionPerformed(evt);
            }
        });

        ffDateFinAjouterDemandeService.setText("          ..   /   ..    /   ..");

        lbAAjouterDemandeService.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lbAAjouterDemandeService.setText("à");

        lbDescriptionAjouterDemandeService.setText("Descrition :");

        btParcourirAjouterDemandeService.setText("Parcourir");
        btParcourirAjouterDemandeService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParcourirAjouterDemandeServiceActionPerformed(evt);
            }
        });

        lbImageAjouterDemandeService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImageAjouterDemandeService.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbImagesAjouterDemandeService.setText("Images :");

        javax.swing.GroupLayout pnDetailServiceLayout = new javax.swing.GroupLayout(pnDetailService);
        pnDetailService.setLayout(pnDetailServiceLayout);
        pnDetailServiceLayout.setHorizontalGroup(
            pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailServiceLayout.createSequentialGroup()
                        .addGroup(pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDateAjouterDemandeService)
                            .addComponent(lbTokensOffertsAjouterDemandeService)
                            .addComponent(lbTitreAjouterDemandeService)
                            .addComponent(lbCategorieAjouterDemandeService)
                            .addComponent(lbDescriptionAjouterDemandeService))
                        .addGap(18, 18, 18)
                        .addGroup(pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTitreAjouterDemandeService)
                            .addComponent(spTokensOffertsAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCategorieAjouterDemandeService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailServiceLayout.createSequentialGroup()
                                .addComponent(lbDuAjouterDemandeService)
                                .addGap(18, 18, 18)
                                .addComponent(ffDateDebutAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(lbAAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ffDateFinAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addComponent(tfDescriptionAjouterDemandeService, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailServiceLayout.createSequentialGroup()
                                .addComponent(lbImageAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btParcourirAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbImagesAjouterDemandeService))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnDetailServiceLayout.setVerticalGroup(
            pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailServiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitreAjouterDemandeService)
                    .addComponent(tfTitreAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategorieAjouterDemandeService)
                    .addComponent(cbCategorieAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTokensOffertsAjouterDemandeService)
                    .addComponent(spTokensOffertsAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDuAjouterDemandeService)
                    .addComponent(ffDateDebutAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAAjouterDemandeService)
                    .addComponent(ffDateFinAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescriptionAjouterDemandeService)
                    .addComponent(tfDescriptionAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnDetailServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailServiceLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbImagesAjouterDemandeService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btParcourirAjouterDemandeService))
                    .addGroup(pnDetailServiceLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbImageAjouterDemandeService, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        btAjouterDemandeService.setText("Ajouter");
        btAjouterDemandeService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterDemandeServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAjouterDemandeServiceLayout = new javax.swing.GroupLayout(pnAjouterDemandeService);
        pnAjouterDemandeService.setLayout(pnAjouterDemandeServiceLayout);
        pnAjouterDemandeServiceLayout.setHorizontalGroup(
            pnAjouterDemandeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAjouterDemandeServiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnAjouterDemandeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAjouterDemandeServiceLayout.createSequentialGroup()
                        .addComponent(btAjouterDemandeService)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAjouterDemandeServiceLayout.createSequentialGroup()
                        .addComponent(pnDetailService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(pnAjouterDemandeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnAjouterDemandeServiceLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lbDemanderService, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(474, Short.MAX_VALUE)))
        );
        pnAjouterDemandeServiceLayout.setVerticalGroup(
            pnAjouterDemandeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAjouterDemandeServiceLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(pnDetailService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAjouterDemandeService)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnAjouterDemandeServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnAjouterDemandeServiceLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(lbDemanderService, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );

        getContentPane().add(pnAjouterDemandeService);
        pnAjouterDemandeService.setBounds(30, 60, 610, 370);

        lbBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wolf\\Desktop\\Maquetage\\src\\Images\\fond1.png")); // NOI18N
        getContentPane().add(lbBackground);
        lbBackground.setBounds(0, 0, 660, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ffDateDebutAjouterDemandeServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffDateDebutAjouterDemandeServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffDateDebutAjouterDemandeServiceActionPerformed

    private void btAjouterDemandeServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterDemandeServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAjouterDemandeServiceActionPerformed

    private void btParcourirAjouterDemandeServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParcourirAjouterDemandeServiceActionPerformed
        ModifierPhoto modifPhoto = new ModifierPhoto();
        modifPhoto.setVisible(true);
    }//GEN-LAST:event_btParcourirAjouterDemandeServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterDemandeDeService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterDemandeDeService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterDemandeDeService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterDemandeDeService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterDemandeDeService().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouterDemandeService;
    private javax.swing.JButton btParcourirAjouterDemandeService;
    private javax.swing.JComboBox cbCategorieAjouterDemandeService;
    private javax.swing.JFormattedTextField ffDateDebutAjouterDemandeService;
    private javax.swing.JFormattedTextField ffDateFinAjouterDemandeService;
    private javax.swing.JLabel lbAAjouterDemandeService;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbCategorieAjouterDemandeService;
    private javax.swing.JLabel lbDateAjouterDemandeService;
    private javax.swing.JLabel lbDemanderService;
    private javax.swing.JLabel lbDescriptionAjouterDemandeService;
    private javax.swing.JLabel lbDuAjouterDemandeService;
    private javax.swing.JLabel lbImageAjouterDemandeService;
    private javax.swing.JLabel lbImagesAjouterDemandeService;
    private javax.swing.JLabel lbTitreAjouterDemandeService;
    private javax.swing.JLabel lbTokensOffertsAjouterDemandeService;
    private javax.swing.JPanel pnAjouterDemandeService;
    private javax.swing.JPanel pnDetailService;
    private javax.swing.JSpinner spTokensOffertsAjouterDemandeService;
    private javax.swing.JTextField tfDescriptionAjouterDemandeService;
    private javax.swing.JTextField tfTitreAjouterDemandeService;
    // End of variables declaration//GEN-END:variables
}
