/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maquetage;

/**
 *
 * @author Wolf
 */
public class FormulaireInscription extends javax.swing.JFrame {

    /**
     * Creates new form FormulaireInscription
     */
    public FormulaireInscription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInscription = new javax.swing.JPanel();
        tfNomFormulaireInscription = new javax.swing.JTextField();
        tfPrenomFormulaireInscription = new javax.swing.JTextField();
        tfEmailFormulaireInscription = new javax.swing.JTextField();
        tfLoginFormulaireInscription = new javax.swing.JTextField();
        pfMotDePasseFormulaireInscription = new javax.swing.JPasswordField();
        tfTelephoneFormulaireInscription = new javax.swing.JTextField();
        tfAdresseFormulaireInscription = new javax.swing.JTextField();
        lbPrenomFormulaireInscription = new javax.swing.JLabel();
        lbEmailFormulaireInscription = new javax.swing.JLabel();
        lbLoginFormulaireInscription = new javax.swing.JLabel();
        lbMotDePasseFormulaireInscription = new javax.swing.JLabel();
        lbTelephoneFormulaireInscription = new javax.swing.JLabel();
        lbAvatarFormulaireInscription = new javax.swing.JLabel();
        lbAdresseFormulaireInscription = new javax.swing.JLabel();
        btParcourirFormulaireInscription = new javax.swing.JButton();
        lbNomFormulaireInscription = new javax.swing.JLabel();
        btValiderFormulaireInscription = new javax.swing.JButton();
        lbBackgroundFormulaireInscription = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(650, 490));
        setPreferredSize(new java.awt.Dimension(650, 490));
        getContentPane().setLayout(null);

        pInscription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Inscription", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24), new java.awt.Color(241, 0, 48))); // NOI18N
        pInscription.setForeground(new java.awt.Color(241, 0, 48));
        pInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        pInscription.setOpaque(false);
        pInscription.setLayout(null);

        tfNomFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        tfNomFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        tfNomFormulaireInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomFormulaireInscriptionActionPerformed(evt);
            }
        });
        pInscription.add(tfNomFormulaireInscription);
        tfNomFormulaireInscription.setBounds(170, 50, 130, 22);

        tfPrenomFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        tfPrenomFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        pInscription.add(tfPrenomFormulaireInscription);
        tfPrenomFormulaireInscription.setBounds(170, 80, 130, 22);

        tfEmailFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        tfEmailFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        pInscription.add(tfEmailFormulaireInscription);
        tfEmailFormulaireInscription.setBounds(170, 110, 130, 22);

        tfLoginFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        tfLoginFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        pInscription.add(tfLoginFormulaireInscription);
        tfLoginFormulaireInscription.setBounds(170, 140, 130, 22);

        pfMotDePasseFormulaireInscription.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pfMotDePasseFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        pfMotDePasseFormulaireInscription.setText("jPasswordField1");
        pfMotDePasseFormulaireInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfMotDePasseFormulaireInscriptionActionPerformed(evt);
            }
        });
        pInscription.add(pfMotDePasseFormulaireInscription);
        pfMotDePasseFormulaireInscription.setBounds(170, 170, 130, 23);

        tfTelephoneFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        tfTelephoneFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        tfTelephoneFormulaireInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelephoneFormulaireInscriptionActionPerformed(evt);
            }
        });
        pInscription.add(tfTelephoneFormulaireInscription);
        tfTelephoneFormulaireInscription.setBounds(170, 200, 130, 22);

        tfAdresseFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        tfAdresseFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        tfAdresseFormulaireInscription.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pInscription.add(tfAdresseFormulaireInscription);
        tfAdresseFormulaireInscription.setBounds(170, 230, 130, 22);

        lbPrenomFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lbPrenomFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        lbPrenomFormulaireInscription.setText("Prénom");
        pInscription.add(lbPrenomFormulaireInscription);
        lbPrenomFormulaireInscription.setBounds(40, 80, 80, 20);

        lbEmailFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lbEmailFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        lbEmailFormulaireInscription.setText("Email");
        pInscription.add(lbEmailFormulaireInscription);
        lbEmailFormulaireInscription.setBounds(40, 110, 80, 20);

        lbLoginFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lbLoginFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        lbLoginFormulaireInscription.setText("Login");
        pInscription.add(lbLoginFormulaireInscription);
        lbLoginFormulaireInscription.setBounds(40, 140, 80, 20);

        lbMotDePasseFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lbMotDePasseFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        lbMotDePasseFormulaireInscription.setText("Mot de passe");
        pInscription.add(lbMotDePasseFormulaireInscription);
        lbMotDePasseFormulaireInscription.setBounds(40, 170, 80, 20);

        lbTelephoneFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lbTelephoneFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        lbTelephoneFormulaireInscription.setText("Téléphone");
        pInscription.add(lbTelephoneFormulaireInscription);
        lbTelephoneFormulaireInscription.setBounds(40, 200, 80, 20);

        lbAvatarFormulaireInscription.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wolf\\Desktop\\Maquetage\\src\\Images\\Avatar.png")); // NOI18N
        pInscription.add(lbAvatarFormulaireInscription);
        lbAvatarFormulaireInscription.setBounds(360, 70, 90, 90);

        lbAdresseFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lbAdresseFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        lbAdresseFormulaireInscription.setText("Adresse");
        pInscription.add(lbAdresseFormulaireInscription);
        lbAdresseFormulaireInscription.setBounds(40, 230, 80, 20);

        btParcourirFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btParcourirFormulaireInscription.setForeground(new java.awt.Color(68, 0, 238));
        btParcourirFormulaireInscription.setText("Parcourir...");
        btParcourirFormulaireInscription.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btParcourirFormulaireInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParcourirFormulaireInscriptionActionPerformed(evt);
            }
        });
        pInscription.add(btParcourirFormulaireInscription);
        btParcourirFormulaireInscription.setBounds(360, 180, 90, 23);

        lbNomFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lbNomFormulaireInscription.setForeground(new java.awt.Color(241, 0, 48));
        lbNomFormulaireInscription.setText("Nom");
        pInscription.add(lbNomFormulaireInscription);
        lbNomFormulaireInscription.setBounds(40, 50, 80, 20);

        btValiderFormulaireInscription.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btValiderFormulaireInscription.setForeground(new java.awt.Color(68, 0, 238));
        btValiderFormulaireInscription.setText("Valider");
        pInscription.add(btValiderFormulaireInscription);
        btValiderFormulaireInscription.setBounds(190, 270, 90, 25);

        getContentPane().add(pInscription);
        pInscription.setBounds(90, 60, 490, 320);

        lbBackgroundFormulaireInscription.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wolf\\Desktop\\Maquetage\\src\\Images\\fond1.png")); // NOI18N
        getContentPane().add(lbBackgroundFormulaireInscription);
        lbBackgroundFormulaireInscription.setBounds(0, 0, 650, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomFormulaireInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomFormulaireInscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomFormulaireInscriptionActionPerformed

    private void pfMotDePasseFormulaireInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfMotDePasseFormulaireInscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfMotDePasseFormulaireInscriptionActionPerformed

    private void tfTelephoneFormulaireInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelephoneFormulaireInscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelephoneFormulaireInscriptionActionPerformed

    private void btParcourirFormulaireInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParcourirFormulaireInscriptionActionPerformed
        ModifierPhoto modifPhoto = new ModifierPhoto();
        modifPhoto.setVisible(true);
    }//GEN-LAST:event_btParcourirFormulaireInscriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulaireInscription().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btParcourirFormulaireInscription;
    private javax.swing.JButton btValiderFormulaireInscription;
    private javax.swing.JLabel lbAdresseFormulaireInscription;
    private javax.swing.JLabel lbAvatarFormulaireInscription;
    private javax.swing.JLabel lbBackgroundFormulaireInscription;
    private javax.swing.JLabel lbEmailFormulaireInscription;
    private javax.swing.JLabel lbLoginFormulaireInscription;
    private javax.swing.JLabel lbMotDePasseFormulaireInscription;
    private javax.swing.JLabel lbNomFormulaireInscription;
    private javax.swing.JLabel lbPrenomFormulaireInscription;
    private javax.swing.JLabel lbTelephoneFormulaireInscription;
    private javax.swing.JPanel pInscription;
    private javax.swing.JPasswordField pfMotDePasseFormulaireInscription;
    private javax.swing.JTextField tfAdresseFormulaireInscription;
    private javax.swing.JTextField tfEmailFormulaireInscription;
    private javax.swing.JTextField tfLoginFormulaireInscription;
    private javax.swing.JTextField tfNomFormulaireInscription;
    private javax.swing.JTextField tfPrenomFormulaireInscription;
    private javax.swing.JTextField tfTelephoneFormulaireInscription;
    // End of variables declaration//GEN-END:variables
}
