/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maquetage;

import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Amine
 */
public class Interface1 extends javax.swing.JFrame {

    /**
     * Creates new form Interface1
     */
    public Interface1() {
        initComponents();
        btModifierObjetOngletMesObjets.setIcon(createIcon("/Images/Modifier.png"));
        btSupprimerObjetOngletMesObjets.setIcon(createIcon("/Images/supprimer.png"));
        btAjouterObjetOngletMesObjets.setIcon(createIcon("/Images/Ajouter.png"));
        btModifierServiceOngletMesServices.setIcon(createIcon("/Images/Modifier.png"));
        btSupprimerServiceOngletMesServices.setIcon(createIcon("/Images/supprimer.png"));
        btAjouterServiceOngletMesServices.setIcon(createIcon("/Images/Ajouter.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpFenetrePrincipale = new javax.swing.JTabbedPane();
        pnOngletRecherche = new javax.swing.JPanel();
        pnDetailsOngletRecherche = new javax.swing.JPanel();
        cbTypeRechcercheOngletRecherche = new javax.swing.JComboBox();
        lbRechercheAvanceeOngletRecherche = new javax.swing.JLabel();
        cbRegionsOngletRecherche = new javax.swing.JComboBox();
        lbRegionOngletRecherche = new javax.swing.JLabel();
        lbTokensOngletRecherche = new javax.swing.JLabel();
        tfMinTokensOngletRecherche = new javax.swing.JTextField();
        tfMaxTokensOngletRecherche = new javax.swing.JTextField();
        lbDeOngletRecherche = new javax.swing.JLabel();
        lbAOngletRecherche = new javax.swing.JLabel();
        lbTypeRechercheOngletRecherche = new javax.swing.JLabel();
        pnCategoriesOngletRecherche = new javax.swing.JPanel();
        lbCategoriesOngletRecherche = new javax.swing.JLabel();
        btChercherOngletRecherche = new javax.swing.JButton();
        cbCategoriesOngletRecherche = new javax.swing.JComboBox();
        spTableauOngletRecherche = new javax.swing.JScrollPane();
        tbResultatOngletRecherche = new javax.swing.JTable();
        pnOngletProfil = new javax.swing.JPanel();
        pnDetailProfilOngletProfil = new javax.swing.JPanel();
        lbTokensOngletProfil = new javax.swing.JLabel();
        lbObtenirTokenOngletProfil = new javax.swing.JLabel();
        pnInformationsOngletProfil = new javax.swing.JPanel();
        lbNomOngletProfil = new javax.swing.JLabel();
        lbNomUtilisateurOngletProfil = new javax.swing.JLabel();
        lbAdresseUtilisateurOngletProfil = new javax.swing.JLabel();
        lbAdresseOngletProfil = new javax.swing.JLabel();
        lbTelephoneOngletProfil = new javax.swing.JLabel();
        lbTelephoneUtilisateurOngletProfil = new javax.swing.JLabel();
        lbMotDePasseUtilisateurOngletProfil = new javax.swing.JLabel();
        lbMotDePasseOngletProfil = new javax.swing.JLabel();
        lbLoginOngletProfil = new javax.swing.JLabel();
        lbLoginUtilisateurOngletProfil = new javax.swing.JLabel();
        lbEmailUtilisateurOngletProfil = new javax.swing.JLabel();
        lbEmailOngletProfil = new javax.swing.JLabel();
        lbPrenomOngletProfil = new javax.swing.JLabel();
        lbPrenomUtilisateurOngletProfil = new javax.swing.JLabel();
        lbCompetencesOngletProfil = new javax.swing.JLabel();
        spCompetencesOngletProfil = new javax.swing.JScrollPane();
        lsCompetencesOngletProfil = new javax.swing.JList();
        btModifierProfilOngletProfil = new javax.swing.JButton();
        lbAvatarOngletProfil = new javax.swing.JLabel();
        pnOngletMesServices = new javax.swing.JPanel();
        lbTokensOngletMesServices = new javax.swing.JLabel();
        lbLienObtenirTokensOngletMesServices = new javax.swing.JLabel();
        spMesServicesOngletMesServices = new javax.swing.JScrollPane();
        tbMesServicesOngletMesServices = new javax.swing.JTable();
        btAjouterServiceOngletMesServices = new javax.swing.JButton();
        btModifierServiceOngletMesServices = new javax.swing.JButton();
        btSupprimerServiceOngletMesServices = new javax.swing.JButton();
        lbPhotoProfilOngletMesServices = new javax.swing.JLabel();
        lbNomPrenomOngletMesServices = new javax.swing.JLabel();
        pnOngletMesObjets = new javax.swing.JPanel();
        lbPhotoProfilOngletMesObjets = new javax.swing.JLabel();
        lbNomPrenomOngletMesObjets = new javax.swing.JLabel();
        lbTokensOngletMesObjets = new javax.swing.JLabel();
        lbLienObtenirTokensOngletMesObjets = new javax.swing.JLabel();
        spMesObjetsOngletMesObjets = new javax.swing.JScrollPane();
        tbMesObjetsOngletMesObjets = new javax.swing.JTable();
        btAjouterObjetOngletMesObjets = new javax.swing.JButton();
        btModifierObjetOngletMesObjets = new javax.swing.JButton();
        btSupprimerObjetOngletMesObjets = new javax.swing.JButton();
        lbBackgroundFenetrePrincipale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 490));
        getContentPane().setLayout(null);

        tpFenetrePrincipale.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        pnOngletRecherche.setOpaque(false);

        pnDetailsOngletRecherche.setName("pnDetailsOngletRecherche"); // NOI18N
        pnDetailsOngletRecherche.setOpaque(false);

        cbTypeRechcercheOngletRecherche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "services", "objets" }));
        cbTypeRechcercheOngletRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeRechcercheOngletRechercheActionPerformed(evt);
            }
        });

        lbRechercheAvanceeOngletRecherche.setText("Recherche avancée :");
        lbRechercheAvanceeOngletRecherche.setName(""); // NOI18N

        cbRegionsOngletRecherche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ariana", "Béja", "Ben Arous", "Bizerte", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kébili", "Kef", "Mahdia", "Manouba", "Médenine", "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliana", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouan" }));
        cbRegionsOngletRecherche.setName("Region"); // NOI18N

        lbRegionOngletRecherche.setText("Région :");

        lbTokensOngletRecherche.setText("Token :");

        tfMaxTokensOngletRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaxTokensOngletRechercheActionPerformed(evt);
            }
        });

        lbDeOngletRecherche.setText("de");

        lbAOngletRecherche.setText("à");

        lbTypeRechercheOngletRecherche.setText("Vous cherchez quoi ?");

        pnCategoriesOngletRecherche.setOpaque(false);

        lbCategoriesOngletRecherche.setText("Catégories :");

        btChercherOngletRecherche.setText("chercher");
        btChercherOngletRecherche.setHideActionText(true);
        btChercherOngletRecherche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btChercherOngletRecherche.setName("btChercherOngletRecherche"); // NOI18N
        btChercherOngletRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChercherOngletRechercheActionPerformed(evt);
            }
        });

        cbCategoriesOngletRecherche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bricolage", "hibergement", "plomberie", "covoiturage", "jardinage", "electricité", "demenagement", "TIC", "mecanique", "reparation", "autres" }));

        javax.swing.GroupLayout pnCategoriesOngletRechercheLayout = new javax.swing.GroupLayout(pnCategoriesOngletRecherche);
        pnCategoriesOngletRecherche.setLayout(pnCategoriesOngletRechercheLayout);
        pnCategoriesOngletRechercheLayout.setHorizontalGroup(
            pnCategoriesOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCategoriesOngletRechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCategoriesOngletRecherche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(pnCategoriesOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btChercherOngletRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCategoriesOngletRecherche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnCategoriesOngletRechercheLayout.setVerticalGroup(
            pnCategoriesOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCategoriesOngletRechercheLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnCategoriesOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoriesOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCategoriesOngletRecherche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btChercherOngletRecherche)
                .addContainerGap())
        );

        spTableauOngletRecherche.setOpaque(false);

        tbResultatOngletRecherche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titre", "Description", "Date de publication", "Tokens"
            }
        ));
        spTableauOngletRecherche.setViewportView(tbResultatOngletRecherche);

        javax.swing.GroupLayout pnDetailsOngletRechercheLayout = new javax.swing.GroupLayout(pnDetailsOngletRecherche);
        pnDetailsOngletRecherche.setLayout(pnDetailsOngletRechercheLayout);
        pnDetailsOngletRechercheLayout.setHorizontalGroup(
            pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailsOngletRechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTableauOngletRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(pnDetailsOngletRechercheLayout.createSequentialGroup()
                        .addGroup(pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDetailsOngletRechercheLayout.createSequentialGroup()
                                .addGroup(pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRegionOngletRecherche)
                                    .addComponent(lbTokensOngletRecherche))
                                .addGroup(pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnDetailsOngletRechercheLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDeOngletRecherche)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfMinTokensOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbAOngletRecherche)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfMaxTokensOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnDetailsOngletRechercheLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(cbRegionsOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lbRechercheAvanceeOngletRecherche)
                            .addGroup(pnDetailsOngletRechercheLayout.createSequentialGroup()
                                .addComponent(lbTypeRechercheOngletRecherche)
                                .addGap(18, 18, 18)
                                .addComponent(cbTypeRechcercheOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(pnCategoriesOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnDetailsOngletRechercheLayout.setVerticalGroup(
            pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailsOngletRechercheLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTypeRechcercheOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTypeRechercheOngletRecherche))
                .addGroup(pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailsOngletRechercheLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbRechercheAvanceeOngletRecherche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRegionsOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRegionOngletRecherche))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnDetailsOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTokensOngletRecherche)
                            .addComponent(tfMinTokensOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMaxTokensOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDeOngletRecherche)
                            .addComponent(lbAOngletRecherche)))
                    .addGroup(pnDetailsOngletRechercheLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(pnCategoriesOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spTableauOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout pnOngletRechercheLayout = new javax.swing.GroupLayout(pnOngletRecherche);
        pnOngletRecherche.setLayout(pnOngletRechercheLayout);
        pnOngletRechercheLayout.setHorizontalGroup(
            pnOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOngletRechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDetailsOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnOngletRechercheLayout.setVerticalGroup(
            pnOngletRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletRechercheLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(pnDetailsOngletRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        tpFenetrePrincipale.addTab("Recherche", pnOngletRecherche);

        pnOngletProfil.setOpaque(false);

        pnDetailProfilOngletProfil.setOpaque(false);

        lbTokensOngletProfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vos Tokens", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lbObtenirTokenOngletProfil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbObtenirTokenOngletProfil.setText("Obtenir plus de Tokens");

        pnInformationsOngletProfil.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informations générales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pnInformationsOngletProfil.setOpaque(false);

        lbNomOngletProfil.setText("Nom :");

        lbNomUtilisateurOngletProfil.setText("Nom_U");

        lbAdresseUtilisateurOngletProfil.setText("Adresse_U");

        lbAdresseOngletProfil.setText("Adresse :");

        lbTelephoneOngletProfil.setText("Téléphone :");

        lbTelephoneUtilisateurOngletProfil.setText("Téléphone_U");

        lbMotDePasseUtilisateurOngletProfil.setText("********");

        lbMotDePasseOngletProfil.setText("Mot de passe :");

        lbLoginOngletProfil.setText("Login  :");

        lbLoginUtilisateurOngletProfil.setText("Login_U");

        lbEmailUtilisateurOngletProfil.setText("Email_U");

        lbEmailOngletProfil.setText("Email :");

        lbPrenomOngletProfil.setText("Prenom :");

        lbPrenomUtilisateurOngletProfil.setText("Prenom_U");

        lbCompetencesOngletProfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCompetencesOngletProfil.setText("Compétences");

        lsCompetencesOngletProfil.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Compétence 1", "Compétence 2", "Compétence 3", "Compétence 4" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spCompetencesOngletProfil.setViewportView(lsCompetencesOngletProfil);

        btModifierProfilOngletProfil.setText("Modifier Profil");
        btModifierProfilOngletProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierProfilOngletProfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnInformationsOngletProfilLayout = new javax.swing.GroupLayout(pnInformationsOngletProfil);
        pnInformationsOngletProfil.setLayout(pnInformationsOngletProfilLayout);
        pnInformationsOngletProfilLayout.setHorizontalGroup(
            pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformationsOngletProfilLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomOngletProfil)
                    .addComponent(lbPrenomOngletProfil)
                    .addComponent(lbEmailOngletProfil)
                    .addComponent(lbLoginOngletProfil)
                    .addComponent(lbMotDePasseOngletProfil)
                    .addComponent(lbTelephoneOngletProfil)
                    .addComponent(lbAdresseOngletProfil))
                .addGap(43, 43, 43)
                .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInformationsOngletProfilLayout.createSequentialGroup()
                        .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMotDePasseUtilisateurOngletProfil)
                            .addComponent(lbLoginUtilisateurOngletProfil)
                            .addComponent(lbEmailUtilisateurOngletProfil)
                            .addComponent(lbPrenomUtilisateurOngletProfil))
                        .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnInformationsOngletProfilLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(spCompetencesOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnInformationsOngletProfilLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lbCompetencesOngletProfil))))
                    .addComponent(lbAdresseUtilisateurOngletProfil)
                    .addComponent(lbTelephoneUtilisateurOngletProfil)
                    .addComponent(lbNomUtilisateurOngletProfil))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInformationsOngletProfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btModifierProfilOngletProfil)
                .addContainerGap())
        );
        pnInformationsOngletProfilLayout.setVerticalGroup(
            pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformationsOngletProfilLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomOngletProfil)
                    .addComponent(lbNomUtilisateurOngletProfil))
                .addGap(18, 18, 18)
                .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInformationsOngletProfilLayout.createSequentialGroup()
                        .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrenomOngletProfil)
                            .addComponent(lbPrenomUtilisateurOngletProfil))
                        .addGap(27, 27, 27)
                        .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmailOngletProfil)
                            .addComponent(lbEmailUtilisateurOngletProfil))
                        .addGap(18, 18, 18)
                        .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLoginOngletProfil)
                            .addComponent(lbLoginUtilisateurOngletProfil))
                        .addGap(18, 18, 18)
                        .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMotDePasseOngletProfil)
                            .addComponent(lbMotDePasseUtilisateurOngletProfil)))
                    .addGroup(pnInformationsOngletProfilLayout.createSequentialGroup()
                        .addComponent(lbCompetencesOngletProfil)
                        .addGap(18, 18, 18)
                        .addComponent(spCompetencesOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelephoneOngletProfil)
                    .addComponent(lbTelephoneUtilisateurOngletProfil))
                .addGap(18, 18, 18)
                .addGroup(pnInformationsOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAdresseOngletProfil)
                    .addComponent(lbAdresseUtilisateurOngletProfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btModifierProfilOngletProfil)
                .addContainerGap())
        );

        lbAvatarOngletProfil.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wolf\\Desktop\\Maquetage\\src\\Images\\Avatar.png")); // NOI18N
        lbAvatarOngletProfil.setText("jLabel1");
        lbAvatarOngletProfil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnDetailProfilOngletProfilLayout = new javax.swing.GroupLayout(pnDetailProfilOngletProfil);
        pnDetailProfilOngletProfil.setLayout(pnDetailProfilOngletProfilLayout);
        pnDetailProfilOngletProfilLayout.setHorizontalGroup(
            pnDetailProfilOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailProfilOngletProfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnInformationsOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnDetailProfilOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailProfilOngletProfilLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnDetailProfilOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTokensOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbObtenirTokenOngletProfil)))
                    .addGroup(pnDetailProfilOngletProfilLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbAvatarOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnDetailProfilOngletProfilLayout.setVerticalGroup(
            pnDetailProfilOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailProfilOngletProfilLayout.createSequentialGroup()
                .addGroup(pnDetailProfilOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailProfilOngletProfilLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbTokensOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbObtenirTokenOngletProfil)
                        .addGap(55, 55, 55)
                        .addComponent(lbAvatarOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDetailProfilOngletProfilLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(pnInformationsOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnOngletProfilLayout = new javax.swing.GroupLayout(pnOngletProfil);
        pnOngletProfil.setLayout(pnOngletProfilLayout);
        pnOngletProfilLayout.setHorizontalGroup(
            pnOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
            .addGroup(pnOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnOngletProfilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnDetailProfilOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnOngletProfilLayout.setVerticalGroup(
            pnOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
            .addGroup(pnOngletProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnOngletProfilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnDetailProfilOngletProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tpFenetrePrincipale.addTab("Profil", pnOngletProfil);

        pnOngletMesServices.setOpaque(false);

        lbTokensOngletMesServices.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tokens", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lbLienObtenirTokensOngletMesServices.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbLienObtenirTokensOngletMesServices.setText("Obtenir plus de Tokens");

        spMesServicesOngletMesServices.setOpaque(false);

        tbMesServicesOngletMesServices.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbMesServicesOngletMesServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titre", "Description", "Date de publication", "Tokens", "Selectionner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spMesServicesOngletMesServices.setViewportView(tbMesServicesOngletMesServices);

        btAjouterServiceOngletMesServices.setText("Ajouter");
        btAjouterServiceOngletMesServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterServiceOngletMesServicesActionPerformed(evt);
            }
        });

        btModifierServiceOngletMesServices.setText("Modifier");
        btModifierServiceOngletMesServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierServiceOngletMesServicesActionPerformed(evt);
            }
        });

        btSupprimerServiceOngletMesServices.setText("Supprimer");

        lbPhotoProfilOngletMesServices.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wolf\\Desktop\\Maquetage\\src\\Images\\Avatar.png")); // NOI18N
        lbPhotoProfilOngletMesServices.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbNomPrenomOngletMesServices.setText("Nom et Prénom");
        lbNomPrenomOngletMesServices.setToolTipText("");

        javax.swing.GroupLayout pnOngletMesServicesLayout = new javax.swing.GroupLayout(pnOngletMesServices);
        pnOngletMesServices.setLayout(pnOngletMesServicesLayout);
        pnOngletMesServicesLayout.setHorizontalGroup(
            pnOngletMesServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOngletMesServicesLayout.createSequentialGroup()
                .addGroup(pnOngletMesServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletMesServicesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spMesServicesOngletMesServices, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                    .addGroup(pnOngletMesServicesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btAjouterServiceOngletMesServices)
                        .addGap(18, 18, 18)
                        .addComponent(btModifierServiceOngletMesServices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSupprimerServiceOngletMesServices))
                    .addGroup(pnOngletMesServicesLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pnOngletMesServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnOngletMesServicesLayout.createSequentialGroup()
                                .addComponent(lbNomPrenomOngletMesServices, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnOngletMesServicesLayout.createSequentialGroup()
                                .addComponent(lbPhotoProfilOngletMesServices, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnOngletMesServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletMesServicesLayout.createSequentialGroup()
                                        .addComponent(lbTokensOngletMesServices, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletMesServicesLayout.createSequentialGroup()
                                        .addComponent(lbLienObtenirTokensOngletMesServices)
                                        .addGap(33, 33, 33)))))))
                .addContainerGap())
        );
        pnOngletMesServicesLayout.setVerticalGroup(
            pnOngletMesServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletMesServicesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnOngletMesServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnOngletMesServicesLayout.createSequentialGroup()
                        .addComponent(lbTokensOngletMesServices, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLienObtenirTokensOngletMesServices))
                    .addComponent(lbPhotoProfilOngletMesServices, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNomPrenomOngletMesServices)
                .addGap(20, 20, 20)
                .addComponent(spMesServicesOngletMesServices, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnOngletMesServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjouterServiceOngletMesServices)
                    .addComponent(btModifierServiceOngletMesServices)
                    .addComponent(btSupprimerServiceOngletMesServices))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tpFenetrePrincipale.addTab("Mes Services", pnOngletMesServices);

        pnOngletMesObjets.setOpaque(false);

        lbPhotoProfilOngletMesObjets.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wolf\\Desktop\\Maquetage\\src\\Images\\Avatar.png")); // NOI18N
        lbPhotoProfilOngletMesObjets.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbNomPrenomOngletMesObjets.setText("Nom et Prénom");
        lbNomPrenomOngletMesObjets.setToolTipText("");

        lbTokensOngletMesObjets.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tokens", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lbLienObtenirTokensOngletMesObjets.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbLienObtenirTokensOngletMesObjets.setText("Obtenir plus de Tokens");

        spMesObjetsOngletMesObjets.setOpaque(false);

        tbMesObjetsOngletMesObjets.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbMesObjetsOngletMesObjets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titre", "Description", "Date de publication", "Tokens", "Selectionner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spMesObjetsOngletMesObjets.setViewportView(tbMesObjetsOngletMesObjets);

        btAjouterObjetOngletMesObjets.setText("Ajouter");
        btAjouterObjetOngletMesObjets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterObjetOngletMesObjetsActionPerformed(evt);
            }
        });

        btModifierObjetOngletMesObjets.setText("Modifier");
        btModifierObjetOngletMesObjets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierObjetOngletMesObjetsActionPerformed(evt);
            }
        });

        btSupprimerObjetOngletMesObjets.setText("Supprimer");
        btSupprimerObjetOngletMesObjets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerObjetOngletMesObjetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnOngletMesObjetsLayout = new javax.swing.GroupLayout(pnOngletMesObjets);
        pnOngletMesObjets.setLayout(pnOngletMesObjetsLayout);
        pnOngletMesObjetsLayout.setHorizontalGroup(
            pnOngletMesObjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOngletMesObjetsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnOngletMesObjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnOngletMesObjetsLayout.createSequentialGroup()
                        .addComponent(lbNomPrenomOngletMesObjets, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnOngletMesObjetsLayout.createSequentialGroup()
                        .addComponent(lbPhotoProfilOngletMesObjets, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnOngletMesObjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletMesObjetsLayout.createSequentialGroup()
                                .addComponent(lbTokensOngletMesObjets, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletMesObjetsLayout.createSequentialGroup()
                                .addComponent(lbLienObtenirTokensOngletMesObjets)
                                .addGap(43, 43, 43))))))
            .addGroup(pnOngletMesObjetsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOngletMesObjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMesObjetsOngletMesObjets, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(pnOngletMesObjetsLayout.createSequentialGroup()
                        .addComponent(btAjouterObjetOngletMesObjets)
                        .addGap(18, 18, 18)
                        .addComponent(btModifierObjetOngletMesObjets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSupprimerObjetOngletMesObjets)))
                .addContainerGap())
        );
        pnOngletMesObjetsLayout.setVerticalGroup(
            pnOngletMesObjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletMesObjetsLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pnOngletMesObjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletMesObjetsLayout.createSequentialGroup()
                        .addComponent(lbTokensOngletMesObjets, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLienObtenirTokensOngletMesObjets)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOngletMesObjetsLayout.createSequentialGroup()
                        .addComponent(lbPhotoProfilOngletMesObjets, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNomPrenomOngletMesObjets)
                        .addGap(18, 18, 18)))
                .addComponent(spMesObjetsOngletMesObjets, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnOngletMesObjetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModifierObjetOngletMesObjets)
                    .addComponent(btAjouterObjetOngletMesObjets)
                    .addComponent(btSupprimerObjetOngletMesObjets))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tpFenetrePrincipale.addTab("Mes Objets", pnOngletMesObjets);

        getContentPane().add(tpFenetrePrincipale);
        tpFenetrePrincipale.setBounds(10, 11, 620, 430);

        lbBackgroundFenetrePrincipale.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wolf\\Desktop\\Maquetage\\src\\Images\\fond1.png")); // NOI18N
        getContentPane().add(lbBackgroundFenetrePrincipale);
        lbBackgroundFenetrePrincipale.setBounds(0, 0, 650, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAjouterServiceOngletMesServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterServiceOngletMesServicesActionPerformed
        AjouterDemandeDeService ads = new AjouterDemandeDeService();
        ads.setVisible(true);
    }//GEN-LAST:event_btAjouterServiceOngletMesServicesActionPerformed

    private void cbTypeRechcercheOngletRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeRechcercheOngletRechercheActionPerformed
        String selectedItem=(String)cbTypeRechcercheOngletRecherche.getSelectedItem();
        lbCategoriesOngletRecherche.setEnabled(true);//labelCategories.setVisible(true);
        cbCategoriesOngletRecherche.setEnabled(true);//categories.setVisible(true);
        if (selectedItem.equals("objets"))
        {lbCategoriesOngletRecherche.setEnabled(false);//labelCategories.setVisible(false);
            cbCategoriesOngletRecherche.setEnabled(false);//categories.setVisible(false);
        }
    }//GEN-LAST:event_cbTypeRechcercheOngletRechercheActionPerformed

    private void tfMaxTokensOngletRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaxTokensOngletRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaxTokensOngletRechercheActionPerformed

    private void btChercherOngletRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChercherOngletRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btChercherOngletRechercheActionPerformed

    private void btModifierServiceOngletMesServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierServiceOngletMesServicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btModifierServiceOngletMesServicesActionPerformed

    private void btModifierProfilOngletProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierProfilOngletProfilActionPerformed
        ModifierProfil modif = new ModifierProfil();
        modif.setVisible(true);
    }//GEN-LAST:event_btModifierProfilOngletProfilActionPerformed

    private void btSupprimerObjetOngletMesObjetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerObjetOngletMesObjetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSupprimerObjetOngletMesObjetsActionPerformed

    private void btModifierObjetOngletMesObjetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierObjetOngletMesObjetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btModifierObjetOngletMesObjetsActionPerformed

    private void btAjouterObjetOngletMesObjetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterObjetOngletMesObjetsActionPerformed
        AjouterObjet ao = new AjouterObjet();
        ao.setVisible(true);
    }//GEN-LAST:event_btAjouterObjetOngletMesObjetsActionPerformed

    //ajouter icon
    
    private ImageIcon createIcon(String path)
    {
        URL url= getClass().getResource(path);
        if(url==null)
        {System.err.println("Unable to load image:"+path);}
        ImageIcon icon=new ImageIcon(url);
        return icon;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /*try {
            //</editor-fold>
    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Interface1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Interface1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Interface1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Interface1.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouterObjetOngletMesObjets;
    private javax.swing.JButton btAjouterServiceOngletMesServices;
    private javax.swing.JButton btChercherOngletRecherche;
    private javax.swing.JButton btModifierObjetOngletMesObjets;
    private javax.swing.JButton btModifierProfilOngletProfil;
    private javax.swing.JButton btModifierServiceOngletMesServices;
    private javax.swing.JButton btSupprimerObjetOngletMesObjets;
    private javax.swing.JButton btSupprimerServiceOngletMesServices;
    private javax.swing.JComboBox cbCategoriesOngletRecherche;
    private javax.swing.JComboBox cbRegionsOngletRecherche;
    private javax.swing.JComboBox cbTypeRechcercheOngletRecherche;
    private javax.swing.JLabel lbAOngletRecherche;
    private javax.swing.JLabel lbAdresseOngletProfil;
    private javax.swing.JLabel lbAdresseUtilisateurOngletProfil;
    private javax.swing.JLabel lbAvatarOngletProfil;
    private javax.swing.JLabel lbBackgroundFenetrePrincipale;
    private javax.swing.JLabel lbCategoriesOngletRecherche;
    private javax.swing.JLabel lbCompetencesOngletProfil;
    private javax.swing.JLabel lbDeOngletRecherche;
    private javax.swing.JLabel lbEmailOngletProfil;
    private javax.swing.JLabel lbEmailUtilisateurOngletProfil;
    private javax.swing.JLabel lbLienObtenirTokensOngletMesObjets;
    private javax.swing.JLabel lbLienObtenirTokensOngletMesServices;
    private javax.swing.JLabel lbLoginOngletProfil;
    private javax.swing.JLabel lbLoginUtilisateurOngletProfil;
    private javax.swing.JLabel lbMotDePasseOngletProfil;
    private javax.swing.JLabel lbMotDePasseUtilisateurOngletProfil;
    private javax.swing.JLabel lbNomOngletProfil;
    private javax.swing.JLabel lbNomPrenomOngletMesObjets;
    private javax.swing.JLabel lbNomPrenomOngletMesServices;
    private javax.swing.JLabel lbNomUtilisateurOngletProfil;
    private javax.swing.JLabel lbObtenirTokenOngletProfil;
    private javax.swing.JLabel lbPhotoProfilOngletMesObjets;
    private javax.swing.JLabel lbPhotoProfilOngletMesServices;
    private javax.swing.JLabel lbPrenomOngletProfil;
    private javax.swing.JLabel lbPrenomUtilisateurOngletProfil;
    private javax.swing.JLabel lbRechercheAvanceeOngletRecherche;
    private javax.swing.JLabel lbRegionOngletRecherche;
    private javax.swing.JLabel lbTelephoneOngletProfil;
    private javax.swing.JLabel lbTelephoneUtilisateurOngletProfil;
    private javax.swing.JLabel lbTokensOngletMesObjets;
    private javax.swing.JLabel lbTokensOngletMesServices;
    private javax.swing.JLabel lbTokensOngletProfil;
    private javax.swing.JLabel lbTokensOngletRecherche;
    private javax.swing.JLabel lbTypeRechercheOngletRecherche;
    private javax.swing.JList lsCompetencesOngletProfil;
    private javax.swing.JPanel pnCategoriesOngletRecherche;
    private javax.swing.JPanel pnDetailProfilOngletProfil;
    private javax.swing.JPanel pnDetailsOngletRecherche;
    private javax.swing.JPanel pnInformationsOngletProfil;
    private javax.swing.JPanel pnOngletMesObjets;
    private javax.swing.JPanel pnOngletMesServices;
    private javax.swing.JPanel pnOngletProfil;
    private javax.swing.JPanel pnOngletRecherche;
    private javax.swing.JScrollPane spCompetencesOngletProfil;
    private javax.swing.JScrollPane spMesObjetsOngletMesObjets;
    private javax.swing.JScrollPane spMesServicesOngletMesServices;
    private javax.swing.JScrollPane spTableauOngletRecherche;
    private javax.swing.JTable tbMesObjetsOngletMesObjets;
    private javax.swing.JTable tbMesServicesOngletMesServices;
    private javax.swing.JTable tbResultatOngletRecherche;
    private javax.swing.JTextField tfMaxTokensOngletRecherche;
    private javax.swing.JTextField tfMinTokensOngletRecherche;
    private javax.swing.JTabbedPane tpFenetrePrincipale;
    // End of variables declaration//GEN-END:variables
}
